site_name: plugin-aws-cloud-service-inven-collector
site_description: "Backstage plugin for AWS Cloud Service Inventory Collector"
nav:
  - About: README.md
  - Guide:
      - KR: ko/index.md
      - EN: en/GUIDE.md
